version: 2

models:
  - name: fact_ventes
    columns:
      - name: MOIS
        data_tests:
          - accepted_values:
              values: ['janvier', 'fevrier', 'mars', 'avril', 'mai', 'juin', 'juillet', 'aout', 'septembre', 'octobre', 'novembre', 'decembre']
      - name: JOUR
        data_tests:
          - accepted_values:
              values: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche']

  - name: fact_factures
    columns:
      - name: MOIS
        data_tests:
          - accepted_values:
              values: ['janvier', 'fevrier', 'mars', 'avril', 'mai', 'juin', 'juillet', 'aout', 'septembre', 'octobre', 'novembre', 'decembre']
      - name: JOUR
        data_tests:
          - accepted_values:
              values: ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche']
